### ISSUE TITLE
关于开源问题。。

### ISSUE THREAD

**Issue by YannLuo** [Root-lee/Put_Flavors_SA#1]
关于提供赛题思路我没有意见。但是还在初赛阶段开放源码，特别是当前阶段的高分源码，感觉会影响其他参赛选手的参赛体验，降低解决问题思路的多样性。建议在初赛过后再开放源码供他人学习，希望能够慎重考虑。

**Comment by Root-lee** [comment]
您好，感谢您的建议。我想解释一下，我这个只是后面一部分的相关思想，此题主要得分点在前半部分预测，您可以看一下我的代码，只是实现了一个经典模拟退火算法，在网上也都是可以搜索到的。此题得高分还是需要靠一个数据预处理和一个好的预测模型，以及模拟退火算法的参数设置，这方面大家都不会相同，想要只靠这份代码拿到高分是不可能的。还是感谢您的批评，帖子里可能对别人有所误导，我更新一下，向大家说明一下。

**Comment by YannLuo** [comment]
没仔细拜读代码就提issue，我确实有点暴躁了。。这个题目里装箱算法是拉不开差距，已有的离线算法已经能达到≤11/9OPT+1的精度了。期待能在复赛面基 :)
